boards/esp32c3-legacy: Add missing include to esp32c3_boot.c
`up_perf_init` defined in `nuttx/arch.h`, if CONFIG_ARCH_PERF_EVENTS enabled the compiler will raise a error:
```
board/esp32c3_boot.c:55:3: error: implicit declaration of function 'up_perf_init' [-Wimplicit-function-declaration]
   55 |   up_perf_init(NULL);
      |   ^~~~~~~~~~~~
board/esp32c3_boot.c:55:16: error: 'NULL' undeclared (first use in this function)
   55 |   up_perf_init(NULL);
      |                ^~~~
board/esp32c3_boot.c:28:1: note: 'NULL' is defined in header '<stddef.h>'; this is probably fixable by adding '#include <stddef.h>'
   27 | #include <nuttx/board.h>
  +++ |+#include <stddef.h>
   28 |
board/esp32c3_boot.c:55:16: note: each undeclared identifier is reported only once for each function it appears in
   55 |   up_perf_init(NULL);
      |                ^~~~
make[1]: *** [/home/huang/Work/nx/nuttx/boards/Board.mk:83: esp32c3_boot.o] Error 1
```